version: '3.9'
services:
  api:
    container_name: api
    build: ./api
    ports:
      - 2000:2000
    restart: unless-stopped
    depends_on:
      - mongo
  web:
    container_name: web
    build: ./app
    ports:
      - 3000:3000
    restart: unless-stopped
  mongo:
    image: 'mongo:latest'
    command: mongod --port 27017 --bind_ip_all
    container_name: mongodb
    hostname: localhost
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
    restart: unless-stopped
  
volumes:
  mongodb_data_container:
